# This is purely for testing purposes! Do not use in production environments
apiVersion: v1
kind: Namespace
metadata:
  name: checkmk-monitoring
---
apiVersion: v1
kind: Service
metadata:
  name: checkmk-internal
  namespace: checkmk-monitoring
  labels:
    run: checkmk-cluster-agent
spec:
  ports:
  - name: agents
    port: 81
    targetPort: 10000
    protocol: TCP
  - name: api
    port: 82
    targetPort: 10050
    protocol: TCP
  selector:
    run: checkmk-cluster-agent
---
apiVersion: v1
kind: Service
metadata:
  name: checkmk-external
  namespace: checkmk-monitoring
  labels:
    run: checkmk-cluster-agent
spec:
  type: NodePort
  ports:
  - name: api
    port: 30035
    nodePort: 30035
    targetPort: 10050
    protocol: TCP
  selector:
    run: checkmk-cluster-agent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkmk-cluster-agent
  namespace: checkmk-monitoring
  labels:
    run: checkmk-cluster-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      run: checkmk-cluster-agent
  template:
    metadata:
      labels:
        run: checkmk-cluster-agent
    spec:
      containers:
      - name: checkmk-cluster-agent
        image: lisapichlertribe29/cluster_agent:0.2
        imagePullPolicy: Always
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        ports:
          - containerPort: 10000
            name: agents
            protocol: TCP
          - containerPort: 10050
            name: api
            protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 2000Mi
          requests:
            cpu: 150m
            memory: 200Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: cadvisor
  name: cadvisor
  namespace: checkmk-monitoring
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  labels:
    app: cadvisor
  name: cadvisor
spec:
  allowedHostPaths:
  - pathPrefix: /
  - pathPrefix: /var/run
  - pathPrefix: /sys
  - pathPrefix: /var/lib/docker
  - pathPrefix: /dev/disk
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: cadvisor
  name: cadvisor
rules:
- apiGroups:
  - policy
  resourceNames:
  - cadvisor
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: cadvisor
  name: cadvisor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cadvisor
subjects:
- kind: ServiceAccount
  name: cadvisor
  namespace: checkmk-monitoring
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: docker/default
  labels:
    app: checkmk-worker-agent
  namespace: checkmk-monitoring
  name: checkmk-worker-agent
spec:
  selector:
    matchLabels:
      app: checkmk-worker-agent
      name: checkmk-worker-agent
  template:
    metadata:
      labels:
        app: checkmk-worker-agent
        name: checkmk-worker-agent
    spec:
      automountServiceAccountToken: false
      containers:
      - image: lisapichlertribe29/worker_agent:0.2
        imagePullPolicy: Always
        name: checkmk-worker-agent
        env:
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        command:
        - /bin/bash
        - -c
        - "printenv > /root/project_env.sh && cron && tail -f /var/log/cron.log"
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 2000Mi
          requests:
            cpu: 150m
            memory: 200Mi
      - image: k8s.gcr.io/cadvisor:v0.30.2
        name: cadvisor
        args:
        - --disable_metrics=tcp,udp,percpu,sched
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 2000Mi
          requests:
            cpu: 150m
            memory: 200Mi
        volumeMounts:
        - mountPath: /rootfs
          name: rootfs
          readOnly: true
        - mountPath: /var/run
          name: var-run
          readOnly: true
        - mountPath: /sys
          name: sys
          readOnly: true
        - mountPath: /var/lib/docker
          name: docker
          readOnly: true
        - mountPath: /dev/disk
          name: disk
          readOnly: true
      serviceAccountName: cadvisor
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /
        name: rootfs
      - hostPath:
          path: /var/run
        name: var-run
      - hostPath:
          path: /sys
        name: sys
      - hostPath:
          path: /var/lib/docker
        name: docker
      - hostPath:
          path: /dev/disk
        name: disk
