apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: checkmk-pv-claim
  namespace: checkmk
spec:
  storageClassName: fast
  resources:
    requests:
      storage: 8Gi
  accessModes:
    - ReadWriteOnce
